name: CI to EC2

on:
  push:
    branches:
      - main

jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Environment
      run: |
        echo "NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}" >> $GITHUB_ENV
        echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> $GITHUB_ENV
        echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> $GITHUB_ENV
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV

    - name: Build and Push Frontend Docker Image
      run: |
        docker build -t dockerbankcicd/frontend:latest \
          --build-arg NEXT_PUBLIC_BACKEND_URL=${{ env.NEXT_PUBLIC_BACKEND_URL }} \
          -f ./frontend/Dockerfile ./frontend
        docker push dockerbankcicd/frontend:latest

    - name: Build and Push Backend Docker Image
      run: |
        docker build -t dockerbankcicd/backend:latest ./backend
        docker push dockerbankcicd/backend:latest

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: "."
        target: "/home/ubuntu/dockerbankcicd"

    - name: Execute deployment script
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/dockerbankcicd
          docker-compose down
          docker pull dockerbankcicd/frontend:latest
          docker pull dockerbankcicd/backend:latest
          docker-compose up -d