name: CI to EC2

on:
  push:
    branches:
      - main

jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: "."
        target: "/home/ubuntu/dockerbankcicd"

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Debug SSH Connection
      run: ssh -Tvvv ${{ secrets.USERNAME }}@${{ secrets.HOST }}
   
    - name: Execute deployment script
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: 22
        script: |
          cd /home/ubuntu/dockerbankcicd
          docker-compose down
          export NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
          export MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
          export MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
          export DB_PORT=${{ secrets.DB_PORT }}
          docker build -t dockerbankcicd/frontend:latest --build-arg NEXT_PUBLIC_BACKEND_URL="$NEXT_PUBLIC_BACKEND_URL" -f ./frontend/Dockerfile ./frontend
          docker build -t dockerbankcicd/backend:latest -f ./backend/Dockerfile ./backend
          docker-compose up -d
